name: Feature request
description: Suggest a new solution or feature.
labels: ["enhancement"]
body:
    - type: textarea
      id: request
      attributes:
          label: What should be added or changed?
          description: For example, a new day or year, or a change to `utils`.
      validations:
          required: true
    - type: textarea
      id: reason
      attributes:
          label: Why is it needed?
      validations:
          required: true
